version: '3.8'
services:
  postgres-db:
    container_name: postgres-db 
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgAdmin:
    depends_on:
      - postgres-db
    container_name: pgAdmin
    image: dpage/pgadmin4:6.17
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
    ports:
        - 8080:80
